%% test_phase6_complex.m — Phase 6: 綜合指令測試（AI 多段腳本鏈路）
%   模擬用戶指令：「同時 y 向 -200，z 向 -100，繞末端 x 軸轉至水平，
%   且末端 z 方向指向正 x 方向，然後同時向前移 500，向下移 600。
%   然後繞末端 z 軸轉 r=100 的圓轉一圈，最後回零位」
%   AI 生成 4 個腳本依次投放，驗證完整鏈路。

% Ensure working directory is tests/ (batch mode may put mfilename in Temp)
if ~strcmp(pwd, 'D:\Document\code\Matlab\robot-agent\tests')
    cd('D:\Document\code\Matlab\robot-agent\tests');
end

addpath(fullfile(pwd, '..', 'src'));
output_dir = fullfile(pwd, 'output');
if ~exist(output_dir, 'dir'), mkdir(output_dir); end

fprintf('=== Phase 6: Complex Multi-Script Integration Test ===\n');

arm = Arm7R();
fig = initRobotFigure(arm, zeros(1,7));
fig.UserData.is_busy = false;
test_in = fullfile(pwd, 'test_incoming_p6');
if exist(test_in, 'dir'), rmdir(test_in, 's'); end
mkdir(test_in);

%% 腳本 1：複合姿態 + 位置調整（Y-200, Z-100 + 繞末端 X 軸 -90°）
fprintf('[P6-T1] Script 1: pose + position adjustment... ');
fid = fopen(fullfile(test_in, 'cmd_01_pose_adjust.m'), 'w');
fprintf(fid, [...
    'ud = fig.UserData;\n' ...
    'arm = ud.arm;\n' ...
    'q0 = ud.current_q;\n' ...
    'T_start = arm.forwardKinematics(q0);\n' ...
    '%% 繞末端 X 軸旋轉 -90°\n' ...
    'axis = T_start(1:3,1);\n' ...
    'theta = -pi/2;\n' ...
    'K = [0 -axis(3) axis(2); axis(3) 0 -axis(1); -axis(2) axis(1) 0];\n' ...
    'R = eye(3) + sin(theta)*K + (1-cos(theta))*(K*K);\n' ...
    'T_end = T_start;\n' ...
    'T_end(1:3,1:3) = R * T_start(1:3,1:3);\n' ...
    'T_end(1:3,4) = T_end(1:3,4) + [0; -200; -100];\n' ...
    '[q_end, err] = arm.inverseKinematics(T_end);\n' ...
    'if err == 0\n' ...
    '    q_traj = quinticTrajectory(q0, q_end, 3, 30);\n' ...
    '    animateRobot(fig, q_traj, 30);\n' ...
    '    fprintf(''[Done] pose_adjust\\n'');\n' ...
    'else\n' ...
    '    fprintf(''[ERR] pose_adjust IK failed\\n'');\n' ...
    'end\n' ...
]);
fclose(fid);
pause(0.15);

processIncomingCommands(test_in, fig);
pause(0.8);
T_after1 = arm.forwardKinematics(fig.UserData.current_q);
fprintf('PASS (pos=[%.1f, %.1f, %.1f])\n', T_after1(1:3,4)');

%% 腳本 2：相對移動（+X 500, -Z 600）
fprintf('[P6-T2] Script 2: relative move (+X500, -Z600)... ');
fid = fopen(fullfile(test_in, 'cmd_02_relative.m'), 'w');
fprintf(fid, [...
    'ud = fig.UserData;\n' ...
    'arm = ud.arm;\n' ...
    'q0 = ud.current_q;\n' ...
    'T_cur = arm.forwardKinematics(q0);\n' ...
    'T_target = T_cur;\n' ...
    'T_target(1:3,4) = T_target(1:3,4) + [500; 0; -600];\n' ...
    '[q1, err] = arm.inverseKinematics(T_target);\n' ...
    'if err == 0\n' ...
    '    q_traj = quinticTrajectory(q0, q1, 4, 30);\n' ...
    '    animateRobot(fig, q_traj, 30);\n' ...
    '    fprintf(''[Done] relative_move\\n'');\n' ...
    'else\n' ...
    '    fprintf(''[ERR] relative_move IK failed\\n'');\n' ...
    'end\n' ...
]);
fclose(fid);
pause(0.15);

processIncomingCommands(test_in, fig);
pause(0.8);
T_after2 = arm.forwardKinematics(fig.UserData.current_q);
fprintf('PASS (pos=[%.1f, %.1f, %.1f])\n', T_after2(1:3,4)');

%% 腳本 3：圓軌跡（繞末端 Z 軸，r=100）
fprintf('[P6-T3] Script 3: circle trajectory (r=100)... ');
fid = fopen(fullfile(test_in, 'cmd_03_circle.m'), 'w');
fprintf(fid, [...
    'ud = fig.UserData;\n' ...
    'arm = ud.arm;\n' ...
    'q0 = ud.current_q;\n' ...
    'T_center = arm.forwardKinematics(q0);\n' ...
    'r = 100;\n' ...
    'n = 60;\n' ...
    'q_circle = [];\n' ...
    'for k = 1:n\n' ...
    '    angle = 2*pi*(k-1)/n;\n' ...
    '    axis_rot = T_center(1:3,3);\n' ...
    '    K = [0 -axis_rot(3) axis_rot(2); axis_rot(3) 0 -axis_rot(1); -axis_rot(2) axis_rot(1) 0];\n' ...
    '    R = eye(3) + sin(angle)*K + (1-cos(angle))*(K*K);\n' ...
    '    T_pt = T_center;\n' ...
    '    T_pt(1:3,1:3) = R * T_center(1:3,1:3);\n' ...
    '    offset = T_center(1:3,2) * r;\n' ...
    '    T_pt(1:3,4) = T_pt(1:3,4) + (eye(3)-R)*offset;\n' ...
    '    [q_pt, err] = arm.inverseKinematics(T_pt);\n' ...
    '    if err == 0\n' ...
    '        q_circle = [q_circle; q_pt];\n' ...
    '    end\n' ...
    'end\n' ...
    'if ~isempty(q_circle)\n' ...
    '    for i = 1:size(q_circle,1)\n' ...
    '        updateRobotFigure(fig, q_circle(i,:));\n' ...
    '        drawnow;\n' ...
    '        pause(1/30);\n' ...
    '    end\n' ...
    '    fig.UserData.current_q = q_circle(end,:);\n' ...
    '    fprintf(''[Done] circle (%%d/%%d points)\\n'', size(q_circle,1), n);\n' ...
    'else\n' ...
    '    fprintf(''[ERR] circle IK all failed\\n'');\n' ...
    'end\n' ...
]);
fclose(fid);
pause(0.15);

processIncomingCommands(test_in, fig);
pause(1.5);
fprintf('PASS\n');

%% 腳本 4：回零位
fprintf('[P6-T4] Script 4: return to home... ');
fid = fopen(fullfile(test_in, 'cmd_04_home.m'), 'w');
fprintf(fid, [...
    'ud = fig.UserData;\n' ...
    'q0 = ud.current_q;\n' ...
    'q1 = zeros(1,7);\n' ...
    'q_traj = quinticTrajectory(q0, q1, 3, 30);\n' ...
    'animateRobot(fig, q_traj, 30);\n' ...
    'fprintf(''[Done] home\\n'');\n' ...
]);
fclose(fid);
pause(0.15);

processIncomingCommands(test_in, fig);
pause(0.8);
assert(max(abs(fig.UserData.current_q)) < 1e-6, 'P6-T4 FAILED: not at home');
fprintf('PASS\n');

%% 清理
close(fig);
rmdir(test_in, 's');

fprintf('\n=== Phase 6: ALL TESTS PASSED ===\n');
