function filepath = generate_robot_cmd(cmd_struct, output_dir)
% generate_robot_cmd 根據結構化指令生成可執行 .m 文件
%   cmd_struct: struct，必須包含 'cmd' 字段
%   output_dir: 輸出目錄，默認為 'incoming/'
%   filepath: 生成的文件路徑

    if nargin < 2 || isempty(output_dir)
        scriptDir = fileparts(mfilename('fullpath'));
        output_dir = fullfile(scriptDir, '..', 'incoming');
    end
    if ~exist(output_dir, 'dir')
        mkdir(output_dir);
    end
    
    timestamp = datestr(now, 'yyyymmdd_HHMMSS_FFF');
    filename = sprintf('cmd_%s_%s.m', timestamp, cmd_struct.cmd);
    filepath = fullfile(output_dir, filename);
    
    code = buildCode(cmd_struct);
    
    fid = fopen(filepath, 'w');
    fwrite(fid, code);
    fclose(fid);
end

%% ===== 內部函數：代碼構建 =====

function code = buildCode(cmd)
    if ~isstruct(cmd) || ~isfield(cmd, 'cmd')
        code = 'error(''Invalid command structure'');';
        return;
    end
    
    % 默認 duration
    if isfield(cmd, 'duration') && ~isempty(cmd.duration)
        duration = cmd.duration;
    else
        duration = 5;
    end
    
    switch cmd.cmd
        case 'home'
            code = buildHomeCode(duration);
        case 'move_to'
            code = buildMoveToCode(cmd, duration);
        case 'joint_move'
            code = buildJointMoveCode(cmd, duration);
        case 'trajectory'
            code = buildTrajectoryCode(cmd, duration);
        case 'get_status'
            code = buildGetStatusCode();
        case 'relative_move'
            code = buildRelativeMoveCode(cmd, duration);
        otherwise
            code = sprintf('error(''Unknown command: %s'');', cmd.cmd);
    end
end

function code = buildHomeCode(duration)
    code = sprintf([...
        '%% Auto-generated: home\n' ...
        'duration = %g;\n' ...
        'fig = findobj(''Type'', ''figure'', ''Name'', ''RobotAgent - 7R Arm'');\n' ...
        'if isempty(fig) || ~isvalid(fig), error(''Figure not found. Run robotagent first.''); end\n' ...
        'ud = fig.UserData;\n' ...
        'arm = ud.arm;\n' ...
        'current_q = ud.current_q;\n' ...
        'q_target = zeros(1, 7);\n' ...
        'q_traj = quinticTrajectory(current_q, q_target, duration, 30);\n' ...
        'for i = 1:size(q_traj, 1)\n' ...
        '    updateRobotFigure(fig, q_traj(i, :));\n' ...
        'drawnow;
' ...
        '    t0 = tic;
' ...
        '    while toc(t0) < 1/30, end
' ...
        'end\n' ...
        'fig.UserData.current_q = q_target;\n' ...
        'fprintf(''[Done] home (duration=%%.1fs)\\n'', duration);\n' ...
    ], duration);
end
function code = buildMoveToCode(cmd, duration)
    pos = cmd.position;
    code = sprintf([...
        '%% Auto-generated: move_to [%.4f, %.4f, %.4f]\n' ...
        'duration = %g;\n' ...
        'fig = findobj(''Type'', ''figure'', ''Name'', ''RobotAgent - 7R Arm'');\n' ...
        'if isempty(fig) || ~isvalid(fig), error(''Figure not found. Run robotagent first.''); end\n' ...
        'ud = fig.UserData;\n' ...
        'arm = ud.arm;\n' ...
        'current_q = ud.current_q;\n' ...
        'T_cur = arm.forwardKinematics(current_q);\n' ...
        'T_target = T_cur;\n' ...
        'T_target(1:3, 4) = [%f; %f; %f];\n' ...
        '[q_target, err] = arm.inverseKinematics(T_target);\n' ...
        'if err ~= 0, error(''move_to: Target unreachable''); end\n' ...
        'steps = max(30, round(duration * 30));\n' ...
        '[~, q_traj, ~] = arm.planTrajectoryCartesian(T_cur, T_target, steps, 0, duration);\n' ...
        'if any(isnan(q_traj(1, :))), q_traj(1, :) = current_q; end\n' ...
        'nan_rows = find(any(isnan(q_traj), 2));\n' ...
        'if ~isempty(nan_rows)\n' ...
        '    first_nan = nan_rows(1);\n' ...
        '    for i = 1:first_nan-1\n' ...
        '        updateRobotFigure(fig, q_traj(i, :));\n' ...
        'drawnow;
' ...
        '    t0 = tic;
' ...
        '    while toc(t0) < 1/30, end
' ...
        '    end\n' ...
        '    fig.UserData.current_q = q_traj(first_nan-1, :);\n' ...
        '    scriptDir = fileparts(mfilename(''fullpath''));
' ...
        '    pause_path = fullfile(scriptDir, ''..'', ''incoming'', sprintf(''pause_%%s.txt'', datestr(now, ''yyyymmdd_HHMMSS_FFF'')));
' ...
        '    fid = fopen(pause_path, ''w'');\n' ...
        '    fprintf(fid, ''current_q: %%s\\n'', mat2str(fig.UserData.current_q));\n' ...
        '    fprintf(fid, ''target_pos: %%s\\n'', mat2str(T_target(1:3,4)''));\n' ...
        '    fprintf(fid, ''failed_step: %%d\\n'', first_nan);\n' ...
        '    fprintf(fid, ''total_steps: %%d\\n'', steps);\n' ...
        '    fprintf(fid, ''cmd: move_to\\n'');\n' ...
        '    fclose(fid);\n' ...
        '    fprintf(''[PAUSE] IK unreachable at step %%d/%%d. State saved to %%s\\n'', first_nan, steps, pause_path);\n' ...
        '    return;\n' ...
        'end\n' ...
        'for i = 1:size(q_traj, 1)\n' ...
        '    updateRobotFigure(fig, q_traj(i, :));\n' ...
        'drawnow;
' ...
        '    t0 = tic;
' ...
        '    while toc(t0) < 1/30, end
' ...
        'end\n' ...
        'fig.UserData.current_q = q_target;\n' ...
        'fprintf(''[Done] move_to (duration=%%.1fs)\\n'', duration);\n' ...
    ], pos(1), pos(2), pos(3), duration, pos(1), pos(2), pos(3));
end

function code = buildJointMoveCode(cmd, duration)
    joint = cmd.joint;
    angle = cmd.angle;
    angle_deg = isfield(cmd, 'angle_deg') && cmd.angle_deg;
    
    if angle_deg
        angle_str = sprintf('deg2rad(%g)', angle);
    else
        angle_str = sprintf('%g', angle);
    end
    
    code = sprintf([...
        '%% Auto-generated: joint_move joint=%d angle=%s\n' ...
        'duration = %g;\n' ...
        'fig = findobj(''Type'', ''figure'', ''Name'', ''RobotAgent - 7R Arm'');\n' ...
        'if isempty(fig) || ~isvalid(fig), error(''Figure not found. Run robotagent first.''); end\n' ...
        'ud = fig.UserData;\n' ...
        'arm = ud.arm;\n' ...
        'current_q = ud.current_q;\n' ...
        'q_target = current_q;\n' ...
        'q_target(%d) = %s;\n' ...
        'q_traj = quinticTrajectory(current_q, q_target, duration, 30);\n' ...
        'for i = 1:size(q_traj, 1)\n' ...
        '    updateRobotFigure(fig, q_traj(i, :));\n' ...
        'drawnow;
' ...
        '    t0 = tic;
' ...
        '    while toc(t0) < 1/30, end
' ...
        'end\n' ...
        'fig.UserData.current_q = q_target;\n' ...
        'fprintf(''[Done] joint_move (duration=%%.1fs)\\n'', duration);\n' ...
    ], joint, num2str(angle), duration, joint, angle_str);
end

function code = buildTrajectoryCode(cmd, duration)
    if ~isfield(cmd, 'type')
        code = 'error(''trajectory requires type'');';
        return;
    end
    
    switch cmd.type
        case 'circle'
            radius = 200;
            if isfield(cmd, 'radius'), radius = cmd.radius; end
            code = sprintf([...
                '%% Auto-generated: trajectory circle radius=%g\n' ...
                'duration = %g;\n' ...
                'fig = findobj(''Type'', ''figure'', ''Name'', ''RobotAgent - 7R Arm'');\n' ...
                'if isempty(fig) || ~isvalid(fig), error(''Figure not found. Run robotagent first.''); end\n' ...
                'ud = fig.UserData;\n' ...
                'arm = ud.arm;\n' ...
                'current_q = ud.current_q;\n' ...
                'T_cur = arm.forwardKinematics(current_q);\n' ...
                'center = T_cur(1:3, 4);\n' ...
                'radius = %g;\n' ...
                'steps = max(20, round(duration * 30));\n' ...
                'theta = linspace(0, 2*pi, steps);\n' ...
                'q_traj = zeros(steps, 7);\n' ...
                'valid_count = 0;\n' ...
                'for i = 1:steps\n' ...
                '    p_i = center + radius * [cos(theta(i)); sin(theta(i)); 0];\n' ...
                '    T_i = [eye(3), p_i; 0, 0, 0, 1];\n' ...
                '    [q_i, err] = arm.inverseKinematics(T_i);\n' ...
                '    if err ~= 0\n' ...
                '        for k = 1:valid_count\n' ...
                '            updateRobotFigure(fig, q_traj(k, :));\n' ...
                'drawnow;
' ...
                '    t0 = tic;
' ...
                '    while toc(t0) < 1/30, end
' ...
                '        end\n' ...
                '        fig.UserData.current_q = q_traj(valid_count, :);\n' ...
                '        scriptDir = fileparts(mfilename(''fullpath''));
' ...
                '        pause_path = fullfile(scriptDir, ''..'', ''incoming'', sprintf(''pause_%%s.txt'', datestr(now, ''yyyymmdd_HHMMSS_FFF'')));
' ...
                '        fid = fopen(pause_path, ''w'');\n' ...
                '        fprintf(fid, ''current_q: %%s\\n'', mat2str(fig.UserData.current_q));\n' ...
                '        fprintf(fid, ''target_pos: %%s\\n'', mat2str(T_i(1:3,4)''));\n' ...
                '        fprintf(fid, ''failed_step: %%d\\n'', i);\n' ...
                '        fprintf(fid, ''total_steps: %%d\\n'', steps);\n' ...
                '        fprintf(fid, ''cmd: trajectory_circle\\n'');\n' ...
                '        fclose(fid);\n' ...
                '        fprintf(''[PAUSE] IK unreachable at step %%d/%%d. State saved to %%s\\n'', i, steps, pause_path);\n' ...
                '        return;\n' ...
                '    end\n' ...
                '    valid_count = valid_count + 1;\n' ...
                '    q_traj(valid_count, :) = q_i;\n' ...
                'end\n' ...
                'q_traj = q_traj(1:valid_count, :);\n' ...
                'if valid_count == 0, error(''circle trajectory: no valid IK''); end\n' ...
                'for i = 1:size(q_traj, 1)\n' ...
                '    updateRobotFigure(fig, q_traj(i, :));\n' ...
                'drawnow;
' ...
                '    t0 = tic;
' ...
                '    while toc(t0) < 1/30, end
' ...
                'end\n' ...
                'fig.UserData.current_q = q_traj(end, :);\n' ...
                'fprintf(''[Done] trajectory circle (duration=%%.1fs)\\n'', duration);\n' ...
            ], radius, duration, radius);
            
        case 'line'
            if ~isfield(cmd, 'target')
                code = 'error(''line trajectory requires target'');';
                return;
            end
            target = cmd.target;
            code = sprintf([...
                '%% Auto-generated: trajectory line target=[%.4f, %.4f, %.4f]\n' ...
                'duration = %g;\n' ...
                'fig = findobj(''Type'', ''figure'', ''Name'', ''RobotAgent - 7R Arm'');\n' ...
                'if isempty(fig) || ~isvalid(fig), error(''Figure not found. Run robotagent first.''); end\n' ...
                'ud = fig.UserData;\n' ...
                'arm = ud.arm;\n' ...
                'current_q = ud.current_q;\n' ...
                'T_cur = arm.forwardKinematics(current_q);\n' ...
                'T_target = [eye(3), [%f; %f; %f]; 0, 0, 0, 1];\n' ...
                '[q_target, err] = arm.inverseKinematics(T_target);\n' ...
                'if err ~= 0, error(''line trajectory: unreachable target''); end\n' ...
                'steps = max(30, round(duration * 30));\n' ...
                '[~, q_traj, ~] = arm.planTrajectoryCartesian(T_cur, T_target, steps, 0, duration);\n' ...
                'if any(isnan(q_traj(1, :))), q_traj(1, :) = current_q; end\n' ...
                'nan_rows = find(any(isnan(q_traj), 2));\n' ...
                'if ~isempty(nan_rows)\n' ...
                '    first_nan = nan_rows(1);\n' ...
                '    for i = 1:first_nan-1\n' ...
                '        updateRobotFigure(fig, q_traj(i, :));\n' ...
                'drawnow;
' ...
                '    t0 = tic;
' ...
                '    while toc(t0) < 1/30, end
' ...
                '    end\n' ...
                '    fig.UserData.current_q = q_traj(first_nan-1, :);\n' ...
                '    scriptDir = fileparts(mfilename(''fullpath''));
' ...
                '    pause_path = fullfile(scriptDir, ''..'', ''incoming'', sprintf(''pause_%%s.txt'', datestr(now, ''yyyymmdd_HHMMSS_FFF'')));
' ...
                '    fid = fopen(pause_path, ''w'');\n' ...
                '    fprintf(fid, ''current_q: %%s\\n'', mat2str(fig.UserData.current_q));\n' ...
                '    fprintf(fid, ''target_pos: %%s\\n'', mat2str(T_target(1:3,4)''));\n' ...
                '    fprintf(fid, ''failed_step: %%d\\n'', first_nan);\n' ...
                '    fprintf(fid, ''total_steps: %%d\\n'', steps);\n' ...
                '    fprintf(fid, ''cmd: trajectory_line\\n'');\n' ...
                '    fclose(fid);\n' ...
                '    fprintf(''[PAUSE] IK unreachable at step %%d/%%d. State saved to %%s\\n'', first_nan, steps, pause_path);\n' ...
                '    return;\n' ...
                'end\n' ...
                'for i = 1:size(q_traj, 1)\n' ...
                '    updateRobotFigure(fig, q_traj(i, :));\n' ...
                'drawnow;
' ...
                '    t0 = tic;
' ...
                '    while toc(t0) < 1/30, end
' ...
                'end\n' ...
                'fig.UserData.current_q = q_target;\n' ...
                'fprintf(''[Done] trajectory line (duration=%%.1fs)\\n'', duration);\n' ...
            ], target(1), target(2), target(3), duration, target(1), target(2), target(3));
            
        otherwise
            code = sprintf('error(''Unknown trajectory type: %s'');', cmd.type);
    end
end

function code = buildGetStatusCode()
    code = sprintf([...
        '%% Auto-generated: get_status\n' ...
        'fig = findobj(''Type'', ''figure'', ''Name'', ''RobotAgent - 7R Arm'');\n' ...
        'if isempty(fig) || ~isvalid(fig), error(''Figure not found. Run robotagent first.''); end\n' ...
        'ud = fig.UserData;\n' ...
        'arm = ud.arm;\n' ...
        'current_q = ud.current_q;\n' ...
        'T_ee = arm.forwardKinematics(current_q);\n' ...
        'fprintf(''=== Robot Status ===\\n'');\n' ...
        'fprintf(''Joint angles (rad): %%s\\n'', mat2str(current_q, 4));\n' ...
        'fprintf(''End-effector position: %%s\\n'', mat2str(T_ee(1:3,4)'', 4));\n' ...
        'fprintf(''End-effector rotation:\\n'');\n' ...
        'disp(T_ee(1:3, 1:3));\n' ...
        'fprintf(''====================\\n'');\n' ...
    ]);
end

function code = buildRelativeMoveCode(cmd, duration)
    axis = cmd.axis;
    dist = cmd.distance;
    axis_idx = find(strcmp(axis, {'x','y','z'}));
    code = sprintf([...
        '%% Auto-generated: relative_move %s=%g\n' ...
        'duration = %g;\n' ...
        'fig = findobj(''Type'', ''figure'', ''Name'', ''RobotAgent - 7R Arm'');\n' ...
        'if isempty(fig) || ~isvalid(fig), error(''Figure not found. Run robotagent first.''); end\n' ...
        'ud = fig.UserData;\n' ...
        'arm = ud.arm;\n' ...
        'current_q = ud.current_q;\n' ...
        'T_cur = arm.forwardKinematics(current_q);\n' ...
        'T_target = T_cur;\n' ...
        'T_target(%d, 4) = T_target(%d, 4) + %f;\n' ...
        '[q_target, err] = arm.inverseKinematics(T_target);\n' ...
        'if err ~= 0, error(''relative_move: target unreachable''); end\n' ...
        'steps = max(30, round(duration * 30));\n' ...
        '[~, q_traj, ~] = arm.planTrajectoryCartesian(T_cur, T_target, steps, 0, duration);\n' ...
        'if any(isnan(q_traj(1, :))), q_traj(1, :) = current_q; end\n' ...
        'nan_rows = find(any(isnan(q_traj), 2));\n' ...
        'if ~isempty(nan_rows)\n' ...
        '    first_nan = nan_rows(1);\n' ...
        '    for i = 1:first_nan-1\n' ...
        '        updateRobotFigure(fig, q_traj(i, :));\n' ...
        'drawnow;
' ...
        '    t0 = tic;
' ...
        '    while toc(t0) < 1/30, end
' ...
        '    end\n' ...
        '    fig.UserData.current_q = q_traj(first_nan-1, :);\n' ...
        '    scriptDir = fileparts(mfilename(''fullpath''));
' ...
        '    pause_path = fullfile(scriptDir, ''..'', ''incoming'', sprintf(''pause_%%s.txt'', datestr(now, ''yyyymmdd_HHMMSS_FFF'')));
' ...
        '    fid = fopen(pause_path, ''w'');\n' ...
        '    fprintf(fid, ''current_q: %%s\\n'', mat2str(fig.UserData.current_q));\n' ...
        '    fprintf(fid, ''target_pos: %%s\\n'', mat2str(T_target(1:3,4)''));\n' ...
        '    fprintf(fid, ''failed_step: %%d\\n'', first_nan);\n' ...
        '    fprintf(fid, ''total_steps: %%d\\n'', steps);\n' ...
        '    fprintf(fid, ''cmd: relative_move\\n'');\n' ...
        '    fclose(fid);\n' ...
        '    fprintf(''[PAUSE] IK unreachable at step %%d/%%d. State saved to %%s\\n'', first_nan, steps, pause_path);\n' ...
        '    return;\n' ...
        'end\n' ...
        'for i = 1:size(q_traj, 1)\n' ...
        '    updateRobotFigure(fig, q_traj(i, :));\n' ...
        'drawnow;
' ...
        '    t0 = tic;
' ...
        '    while toc(t0) < 1/30, end
' ...
        'end\n' ...
        'fig.UserData.current_q = q_target;\n' ...
        'fprintf(''[Done] relative_move %s %g (duration=%%.1fs)\\n'', duration);\n' ...
    ], axis, dist, duration, axis_idx, axis_idx, dist, axis, dist);
end
